// flow-typed signature: dc4b9bb16eda7c0b15579dac0d35f6c7
// flow-typed version: <<STUB>>/ascii-table_v0.0.9/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ascii-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ascii-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ascii-table/ascii-table' {
  declare module.exports: any;
}

declare module 'ascii-table/ascii-table.min' {
  declare module.exports: any;
}

declare module 'ascii-table/example/simple' {
  declare module.exports: any;
}

declare module 'ascii-table/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ascii-table/ascii-table.js' {
  declare module.exports: $Exports<'ascii-table/ascii-table'>;
}
declare module 'ascii-table/ascii-table.min.js' {
  declare module.exports: $Exports<'ascii-table/ascii-table.min'>;
}
declare module 'ascii-table/example/simple.js' {
  declare module.exports: $Exports<'ascii-table/example/simple'>;
}
declare module 'ascii-table/index' {
  declare module.exports: $Exports<'ascii-table'>;
}
declare module 'ascii-table/index.js' {
  declare module.exports: $Exports<'ascii-table'>;
}
declare module 'ascii-table/test.js' {
  declare module.exports: $Exports<'ascii-table/test'>;
}
