// flow-typed signature: 9818da8d0d2558e3943f83feaa18f78f
// flow-typed version: <<STUB>>/d3-axis_v1.0.8/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-axis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-axis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-axis/build/d3-axis' {
  declare module.exports: any;
}

declare module 'd3-axis/build/d3-axis.min' {
  declare module.exports: any;
}

declare module 'd3-axis/src/array' {
  declare module.exports: any;
}

declare module 'd3-axis/src/axis' {
  declare module.exports: any;
}

declare module 'd3-axis/src/identity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-axis/build/d3-axis.js' {
  declare module.exports: $Exports<'d3-axis/build/d3-axis'>;
}
declare module 'd3-axis/build/d3-axis.min.js' {
  declare module.exports: $Exports<'d3-axis/build/d3-axis.min'>;
}
declare module 'd3-axis/index' {
  declare module.exports: $Exports<'d3-axis'>;
}
declare module 'd3-axis/index.js' {
  declare module.exports: $Exports<'d3-axis'>;
}
declare module 'd3-axis/src/array.js' {
  declare module.exports: $Exports<'d3-axis/src/array'>;
}
declare module 'd3-axis/src/axis.js' {
  declare module.exports: $Exports<'d3-axis/src/axis'>;
}
declare module 'd3-axis/src/identity.js' {
  declare module.exports: $Exports<'d3-axis/src/identity'>;
}
