// flow-typed signature: 0f294a08b152857aad2cc3f204ac491a
// flow-typed version: <<STUB>>/d3-color_v1.0.3/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-color/build/d3-color' {
  declare module.exports: any;
}

declare module 'd3-color/build/d3-color.min' {
  declare module.exports: any;
}

declare module 'd3-color/src/color' {
  declare module.exports: any;
}

declare module 'd3-color/src/cubehelix' {
  declare module.exports: any;
}

declare module 'd3-color/src/define' {
  declare module.exports: any;
}

declare module 'd3-color/src/lab' {
  declare module.exports: any;
}

declare module 'd3-color/src/math' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-color/build/d3-color.js' {
  declare module.exports: $Exports<'d3-color/build/d3-color'>;
}
declare module 'd3-color/build/d3-color.min.js' {
  declare module.exports: $Exports<'d3-color/build/d3-color.min'>;
}
declare module 'd3-color/index' {
  declare module.exports: $Exports<'d3-color'>;
}
declare module 'd3-color/index.js' {
  declare module.exports: $Exports<'d3-color'>;
}
declare module 'd3-color/src/color.js' {
  declare module.exports: $Exports<'d3-color/src/color'>;
}
declare module 'd3-color/src/cubehelix.js' {
  declare module.exports: $Exports<'d3-color/src/cubehelix'>;
}
declare module 'd3-color/src/define.js' {
  declare module.exports: $Exports<'d3-color/src/define'>;
}
declare module 'd3-color/src/lab.js' {
  declare module.exports: $Exports<'d3-color/src/lab'>;
}
declare module 'd3-color/src/math.js' {
  declare module.exports: $Exports<'d3-color/src/math'>;
}
