// flow-typed signature: ba58cb0334a436af2a90dd89df9d17db
// flow-typed version: <<STUB>>/d3-interpolate_v1.1.6/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-interpolate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-interpolate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-interpolate/build/d3-interpolate' {
  declare module.exports: any;
}

declare module 'd3-interpolate/build/d3-interpolate.min' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/array' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/basis' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/basisClosed' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/color' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/constant' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/cubehelix' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/date' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/hcl' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/hsl' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/lab' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/number' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/object' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/quantize' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/rgb' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/round' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/string' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/transform/decompose' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/transform/index' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/transform/parse' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/value' {
  declare module.exports: any;
}

declare module 'd3-interpolate/src/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-interpolate/build/d3-interpolate.js' {
  declare module.exports: $Exports<'d3-interpolate/build/d3-interpolate'>;
}
declare module 'd3-interpolate/build/d3-interpolate.min.js' {
  declare module.exports: $Exports<'d3-interpolate/build/d3-interpolate.min'>;
}
declare module 'd3-interpolate/index' {
  declare module.exports: $Exports<'d3-interpolate'>;
}
declare module 'd3-interpolate/index.js' {
  declare module.exports: $Exports<'d3-interpolate'>;
}
declare module 'd3-interpolate/src/array.js' {
  declare module.exports: $Exports<'d3-interpolate/src/array'>;
}
declare module 'd3-interpolate/src/basis.js' {
  declare module.exports: $Exports<'d3-interpolate/src/basis'>;
}
declare module 'd3-interpolate/src/basisClosed.js' {
  declare module.exports: $Exports<'d3-interpolate/src/basisClosed'>;
}
declare module 'd3-interpolate/src/color.js' {
  declare module.exports: $Exports<'d3-interpolate/src/color'>;
}
declare module 'd3-interpolate/src/constant.js' {
  declare module.exports: $Exports<'d3-interpolate/src/constant'>;
}
declare module 'd3-interpolate/src/cubehelix.js' {
  declare module.exports: $Exports<'d3-interpolate/src/cubehelix'>;
}
declare module 'd3-interpolate/src/date.js' {
  declare module.exports: $Exports<'d3-interpolate/src/date'>;
}
declare module 'd3-interpolate/src/hcl.js' {
  declare module.exports: $Exports<'d3-interpolate/src/hcl'>;
}
declare module 'd3-interpolate/src/hsl.js' {
  declare module.exports: $Exports<'d3-interpolate/src/hsl'>;
}
declare module 'd3-interpolate/src/lab.js' {
  declare module.exports: $Exports<'d3-interpolate/src/lab'>;
}
declare module 'd3-interpolate/src/number.js' {
  declare module.exports: $Exports<'d3-interpolate/src/number'>;
}
declare module 'd3-interpolate/src/object.js' {
  declare module.exports: $Exports<'d3-interpolate/src/object'>;
}
declare module 'd3-interpolate/src/quantize.js' {
  declare module.exports: $Exports<'d3-interpolate/src/quantize'>;
}
declare module 'd3-interpolate/src/rgb.js' {
  declare module.exports: $Exports<'d3-interpolate/src/rgb'>;
}
declare module 'd3-interpolate/src/round.js' {
  declare module.exports: $Exports<'d3-interpolate/src/round'>;
}
declare module 'd3-interpolate/src/string.js' {
  declare module.exports: $Exports<'d3-interpolate/src/string'>;
}
declare module 'd3-interpolate/src/transform/decompose.js' {
  declare module.exports: $Exports<'d3-interpolate/src/transform/decompose'>;
}
declare module 'd3-interpolate/src/transform/index.js' {
  declare module.exports: $Exports<'d3-interpolate/src/transform/index'>;
}
declare module 'd3-interpolate/src/transform/parse.js' {
  declare module.exports: $Exports<'d3-interpolate/src/transform/parse'>;
}
declare module 'd3-interpolate/src/value.js' {
  declare module.exports: $Exports<'d3-interpolate/src/value'>;
}
declare module 'd3-interpolate/src/zoom.js' {
  declare module.exports: $Exports<'d3-interpolate/src/zoom'>;
}
