// flow-typed signature: fc2561525e245531b4f4740aa8eaf791
// flow-typed version: <<STUB>>/d3-time-format_v2.1.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-time-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-time-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-time-format/build/d3-time-format' {
  declare module.exports: any;
}

declare module 'd3-time-format/build/d3-time-format.min' {
  declare module.exports: any;
}

declare module 'd3-time-format/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-time-format/src/defaultLocale' {
  declare module.exports: any;
}

declare module 'd3-time-format/src/isoFormat' {
  declare module.exports: any;
}

declare module 'd3-time-format/src/isoParse' {
  declare module.exports: any;
}

declare module 'd3-time-format/src/locale' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-time-format/build/d3-time-format.js' {
  declare module.exports: $Exports<'d3-time-format/build/d3-time-format'>;
}
declare module 'd3-time-format/build/d3-time-format.min.js' {
  declare module.exports: $Exports<'d3-time-format/build/d3-time-format.min'>;
}
declare module 'd3-time-format/index' {
  declare module.exports: $Exports<'d3-time-format'>;
}
declare module 'd3-time-format/index.js' {
  declare module.exports: $Exports<'d3-time-format'>;
}
declare module 'd3-time-format/rollup.config.js' {
  declare module.exports: $Exports<'d3-time-format/rollup.config'>;
}
declare module 'd3-time-format/src/defaultLocale.js' {
  declare module.exports: $Exports<'d3-time-format/src/defaultLocale'>;
}
declare module 'd3-time-format/src/isoFormat.js' {
  declare module.exports: $Exports<'d3-time-format/src/isoFormat'>;
}
declare module 'd3-time-format/src/isoParse.js' {
  declare module.exports: $Exports<'d3-time-format/src/isoParse'>;
}
declare module 'd3-time-format/src/locale.js' {
  declare module.exports: $Exports<'d3-time-format/src/locale'>;
}
