// flow-typed signature: 1f80a5a0446299ed17353b169bfdc60d
// flow-typed version: <<STUB>>/d3-transition_v1.1.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-transition/build/d3-transition' {
  declare module.exports: any;
}

declare module 'd3-transition/build/d3-transition.min' {
  declare module.exports: any;
}

declare module 'd3-transition/src/active' {
  declare module.exports: any;
}

declare module 'd3-transition/src/interrupt' {
  declare module.exports: any;
}

declare module 'd3-transition/src/selection/index' {
  declare module.exports: any;
}

declare module 'd3-transition/src/selection/interrupt' {
  declare module.exports: any;
}

declare module 'd3-transition/src/selection/transition' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/attr' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/attrTween' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/delay' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/duration' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/ease' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/filter' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/index' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/interpolate' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/merge' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/on' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/remove' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/schedule' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/select' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/selectAll' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/selection' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/style' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/styleTween' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/text' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/transition' {
  declare module.exports: any;
}

declare module 'd3-transition/src/transition/tween' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-transition/build/d3-transition.js' {
  declare module.exports: $Exports<'d3-transition/build/d3-transition'>;
}
declare module 'd3-transition/build/d3-transition.min.js' {
  declare module.exports: $Exports<'d3-transition/build/d3-transition.min'>;
}
declare module 'd3-transition/index' {
  declare module.exports: $Exports<'d3-transition'>;
}
declare module 'd3-transition/index.js' {
  declare module.exports: $Exports<'d3-transition'>;
}
declare module 'd3-transition/src/active.js' {
  declare module.exports: $Exports<'d3-transition/src/active'>;
}
declare module 'd3-transition/src/interrupt.js' {
  declare module.exports: $Exports<'d3-transition/src/interrupt'>;
}
declare module 'd3-transition/src/selection/index.js' {
  declare module.exports: $Exports<'d3-transition/src/selection/index'>;
}
declare module 'd3-transition/src/selection/interrupt.js' {
  declare module.exports: $Exports<'d3-transition/src/selection/interrupt'>;
}
declare module 'd3-transition/src/selection/transition.js' {
  declare module.exports: $Exports<'d3-transition/src/selection/transition'>;
}
declare module 'd3-transition/src/transition/attr.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/attr'>;
}
declare module 'd3-transition/src/transition/attrTween.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/attrTween'>;
}
declare module 'd3-transition/src/transition/delay.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/delay'>;
}
declare module 'd3-transition/src/transition/duration.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/duration'>;
}
declare module 'd3-transition/src/transition/ease.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/ease'>;
}
declare module 'd3-transition/src/transition/filter.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/filter'>;
}
declare module 'd3-transition/src/transition/index.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/index'>;
}
declare module 'd3-transition/src/transition/interpolate.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/interpolate'>;
}
declare module 'd3-transition/src/transition/merge.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/merge'>;
}
declare module 'd3-transition/src/transition/on.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/on'>;
}
declare module 'd3-transition/src/transition/remove.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/remove'>;
}
declare module 'd3-transition/src/transition/schedule.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/schedule'>;
}
declare module 'd3-transition/src/transition/select.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/select'>;
}
declare module 'd3-transition/src/transition/selectAll.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/selectAll'>;
}
declare module 'd3-transition/src/transition/selection.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/selection'>;
}
declare module 'd3-transition/src/transition/style.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/style'>;
}
declare module 'd3-transition/src/transition/styleTween.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/styleTween'>;
}
declare module 'd3-transition/src/transition/text.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/text'>;
}
declare module 'd3-transition/src/transition/transition.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/transition'>;
}
declare module 'd3-transition/src/transition/tween.js' {
  declare module.exports: $Exports<'d3-transition/src/transition/tween'>;
}
