// flow-typed signature: 719682f67538eb21b904230781227b94
// flow-typed version: <<STUB>>/date-fns_v^1.29.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-fns/add_days' {
  declare module.exports: any;
}

declare module 'date-fns/add_hours' {
  declare module.exports: any;
}

declare module 'date-fns/add_iso_years' {
  declare module.exports: any;
}

declare module 'date-fns/add_milliseconds' {
  declare module.exports: any;
}

declare module 'date-fns/add_minutes' {
  declare module.exports: any;
}

declare module 'date-fns/add_months' {
  declare module.exports: any;
}

declare module 'date-fns/add_quarters' {
  declare module.exports: any;
}

declare module 'date-fns/add_seconds' {
  declare module.exports: any;
}

declare module 'date-fns/add_weeks' {
  declare module.exports: any;
}

declare module 'date-fns/add_years' {
  declare module.exports: any;
}

declare module 'date-fns/are_ranges_overlapping' {
  declare module.exports: any;
}

declare module 'date-fns/closest_index_to' {
  declare module.exports: any;
}

declare module 'date-fns/closest_to' {
  declare module.exports: any;
}

declare module 'date-fns/compare_asc' {
  declare module.exports: any;
}

declare module 'date-fns/compare_desc' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_days' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_iso_weeks' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_iso_years' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_months' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_quarters' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_weeks' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_years' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_days' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_hours' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_iso_years' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_milliseconds' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_minutes' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_months' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_quarters' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_seconds' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_weeks' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_years' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words_strict' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words_to_now' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words' {
  declare module.exports: any;
}

declare module 'date-fns/each_day' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_day' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_hour' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_minute' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_month' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_second' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_today' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_tomorrow' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_week' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_year' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_yesterday' {
  declare module.exports: any;
}

declare module 'date-fns/format' {
  declare module.exports: any;
}

declare module 'date-fns/get_date' {
  declare module.exports: any;
}

declare module 'date-fns/get_day_of_year' {
  declare module.exports: any;
}

declare module 'date-fns/get_day' {
  declare module.exports: any;
}

declare module 'date-fns/get_days_in_month' {
  declare module.exports: any;
}

declare module 'date-fns/get_days_in_year' {
  declare module.exports: any;
}

declare module 'date-fns/get_hours' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_day' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_weeks_in_year' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/get_milliseconds' {
  declare module.exports: any;
}

declare module 'date-fns/get_minutes' {
  declare module.exports: any;
}

declare module 'date-fns/get_month' {
  declare module.exports: any;
}

declare module 'date-fns/get_overlapping_days_in_ranges' {
  declare module.exports: any;
}

declare module 'date-fns/get_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/get_seconds' {
  declare module.exports: any;
}

declare module 'date-fns/get_time' {
  declare module.exports: any;
}

declare module 'date-fns/get_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_after' {
  declare module.exports: any;
}

declare module 'date-fns/is_before' {
  declare module.exports: any;
}

declare module 'date-fns/is_date' {
  declare module.exports: any;
}

declare module 'date-fns/is_equal' {
  declare module.exports: any;
}

declare module 'date-fns/is_first_day_of_month' {
  declare module.exports: any;
}

declare module 'date-fns/is_friday' {
  declare module.exports: any;
}

declare module 'date-fns/is_future' {
  declare module.exports: any;
}

declare module 'date-fns/is_last_day_of_month' {
  declare module.exports: any;
}

declare module 'date-fns/is_leap_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_monday' {
  declare module.exports: any;
}

declare module 'date-fns/is_past' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_day' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_hour' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_minute' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_month' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_second' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_week' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_saturday' {
  declare module.exports: any;
}

declare module 'date-fns/is_sunday' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_hour' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_minute' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_month' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_second' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_week' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_year' {
  declare module.exports: any;
}

declare module 'date-fns/is_thursday' {
  declare module.exports: any;
}

declare module 'date-fns/is_today' {
  declare module.exports: any;
}

declare module 'date-fns/is_tomorrow' {
  declare module.exports: any;
}

declare module 'date-fns/is_tuesday' {
  declare module.exports: any;
}

declare module 'date-fns/is_valid' {
  declare module.exports: any;
}

declare module 'date-fns/is_wednesday' {
  declare module.exports: any;
}

declare module 'date-fns/is_weekend' {
  declare module.exports: any;
}

declare module 'date-fns/is_within_range' {
  declare module.exports: any;
}

declare module 'date-fns/is_yesterday' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_month' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_week' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_year' {
  declare module.exports: any;
}

declare module 'date-fns/locale/_lib/build_formatting_tokens_reg_exp' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw/build_distance_in_words_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw/build_format_locale' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw' {
  declare module.exports: any;
}

declare module 'date-fns/max' {
  declare module.exports: any;
}

declare module 'date-fns/min' {
  declare module.exports: any;
}

declare module 'date-fns/parse' {
  declare module.exports: any;
}

declare module 'date-fns/set_date' {
  declare module.exports: any;
}

declare module 'date-fns/set_day_of_year' {
  declare module.exports: any;
}

declare module 'date-fns/set_day' {
  declare module.exports: any;
}

declare module 'date-fns/set_hours' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_day' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/set_milliseconds' {
  declare module.exports: any;
}

declare module 'date-fns/set_minutes' {
  declare module.exports: any;
}

declare module 'date-fns/set_month' {
  declare module.exports: any;
}

declare module 'date-fns/set_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/set_seconds' {
  declare module.exports: any;
}

declare module 'date-fns/set_year' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_day' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_hour' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_iso_week' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_iso_year' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_minute' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_month' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_quarter' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_second' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_today' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_tomorrow' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_week' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_year' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_yesterday' {
  declare module.exports: any;
}

declare module 'date-fns/sub_days' {
  declare module.exports: any;
}

declare module 'date-fns/sub_hours' {
  declare module.exports: any;
}

declare module 'date-fns/sub_iso_years' {
  declare module.exports: any;
}

declare module 'date-fns/sub_milliseconds' {
  declare module.exports: any;
}

declare module 'date-fns/sub_minutes' {
  declare module.exports: any;
}

declare module 'date-fns/sub_months' {
  declare module.exports: any;
}

declare module 'date-fns/sub_quarters' {
  declare module.exports: any;
}

declare module 'date-fns/sub_seconds' {
  declare module.exports: any;
}

declare module 'date-fns/sub_weeks' {
  declare module.exports: any;
}

declare module 'date-fns/sub_years' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-fns/add_days/index.js' {
  declare module.exports: $Exports<'date-fns/add_days'>;
}
declare module 'date-fns/add_hours/index.js' {
  declare module.exports: $Exports<'date-fns/add_hours'>;
}
declare module 'date-fns/add_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/add_iso_years'>;
}
declare module 'date-fns/add_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/add_milliseconds'>;
}
declare module 'date-fns/add_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/add_minutes'>;
}
declare module 'date-fns/add_months/index.js' {
  declare module.exports: $Exports<'date-fns/add_months'>;
}
declare module 'date-fns/add_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/add_quarters'>;
}
declare module 'date-fns/add_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/add_seconds'>;
}
declare module 'date-fns/add_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/add_weeks'>;
}
declare module 'date-fns/add_years/index.js' {
  declare module.exports: $Exports<'date-fns/add_years'>;
}
declare module 'date-fns/are_ranges_overlapping/index.js' {
  declare module.exports: $Exports<'date-fns/are_ranges_overlapping'>;
}
declare module 'date-fns/closest_index_to/index.js' {
  declare module.exports: $Exports<'date-fns/closest_index_to'>;
}
declare module 'date-fns/closest_to/index.js' {
  declare module.exports: $Exports<'date-fns/closest_to'>;
}
declare module 'date-fns/compare_asc/index.js' {
  declare module.exports: $Exports<'date-fns/compare_asc'>;
}
declare module 'date-fns/compare_desc/index.js' {
  declare module.exports: $Exports<'date-fns/compare_desc'>;
}
declare module 'date-fns/difference_in_calendar_days/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_days'>;
}
declare module 'date-fns/difference_in_calendar_iso_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_iso_weeks'>;
}
declare module 'date-fns/difference_in_calendar_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_iso_years'>;
}
declare module 'date-fns/difference_in_calendar_months/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_months'>;
}
declare module 'date-fns/difference_in_calendar_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_quarters'>;
}
declare module 'date-fns/difference_in_calendar_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_weeks'>;
}
declare module 'date-fns/difference_in_calendar_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_years'>;
}
declare module 'date-fns/difference_in_days/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_days'>;
}
declare module 'date-fns/difference_in_hours/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_hours'>;
}
declare module 'date-fns/difference_in_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_iso_years'>;
}
declare module 'date-fns/difference_in_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_milliseconds'>;
}
declare module 'date-fns/difference_in_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_minutes'>;
}
declare module 'date-fns/difference_in_months/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_months'>;
}
declare module 'date-fns/difference_in_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_quarters'>;
}
declare module 'date-fns/difference_in_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_seconds'>;
}
declare module 'date-fns/difference_in_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_weeks'>;
}
declare module 'date-fns/difference_in_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_years'>;
}
declare module 'date-fns/distance_in_words_strict/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words_strict'>;
}
declare module 'date-fns/distance_in_words_to_now/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words_to_now'>;
}
declare module 'date-fns/distance_in_words/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words'>;
}
declare module 'date-fns/each_day/index.js' {
  declare module.exports: $Exports<'date-fns/each_day'>;
}
declare module 'date-fns/end_of_day/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_day'>;
}
declare module 'date-fns/end_of_hour/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_hour'>;
}
declare module 'date-fns/end_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_iso_week'>;
}
declare module 'date-fns/end_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_iso_year'>;
}
declare module 'date-fns/end_of_minute/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_minute'>;
}
declare module 'date-fns/end_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_month'>;
}
declare module 'date-fns/end_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_quarter'>;
}
declare module 'date-fns/end_of_second/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_second'>;
}
declare module 'date-fns/end_of_today/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_today'>;
}
declare module 'date-fns/end_of_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_tomorrow'>;
}
declare module 'date-fns/end_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_week'>;
}
declare module 'date-fns/end_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_year'>;
}
declare module 'date-fns/end_of_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_yesterday'>;
}
declare module 'date-fns/format/index.js' {
  declare module.exports: $Exports<'date-fns/format'>;
}
declare module 'date-fns/get_date/index.js' {
  declare module.exports: $Exports<'date-fns/get_date'>;
}
declare module 'date-fns/get_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_day_of_year'>;
}
declare module 'date-fns/get_day/index.js' {
  declare module.exports: $Exports<'date-fns/get_day'>;
}
declare module 'date-fns/get_days_in_month/index.js' {
  declare module.exports: $Exports<'date-fns/get_days_in_month'>;
}
declare module 'date-fns/get_days_in_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_days_in_year'>;
}
declare module 'date-fns/get_hours/index.js' {
  declare module.exports: $Exports<'date-fns/get_hours'>;
}
declare module 'date-fns/get_iso_day/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_day'>;
}
declare module 'date-fns/get_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_week'>;
}
declare module 'date-fns/get_iso_weeks_in_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_weeks_in_year'>;
}
declare module 'date-fns/get_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_year'>;
}
declare module 'date-fns/get_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/get_milliseconds'>;
}
declare module 'date-fns/get_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/get_minutes'>;
}
declare module 'date-fns/get_month/index.js' {
  declare module.exports: $Exports<'date-fns/get_month'>;
}
declare module 'date-fns/get_overlapping_days_in_ranges/index.js' {
  declare module.exports: $Exports<'date-fns/get_overlapping_days_in_ranges'>;
}
declare module 'date-fns/get_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/get_quarter'>;
}
declare module 'date-fns/get_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/get_seconds'>;
}
declare module 'date-fns/get_time/index.js' {
  declare module.exports: $Exports<'date-fns/get_time'>;
}
declare module 'date-fns/get_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_year'>;
}
declare module 'date-fns' {
  declare module.exports: $Exports<'date-fns'>;
}
declare module 'date-fns/index.js' {
  declare module.exports: $Exports<'date-fns'>;
}
declare module 'date-fns/is_after/index.js' {
  declare module.exports: $Exports<'date-fns/is_after'>;
}
declare module 'date-fns/is_before/index.js' {
  declare module.exports: $Exports<'date-fns/is_before'>;
}
declare module 'date-fns/is_date/index.js' {
  declare module.exports: $Exports<'date-fns/is_date'>;
}
declare module 'date-fns/is_equal/index.js' {
  declare module.exports: $Exports<'date-fns/is_equal'>;
}
declare module 'date-fns/is_first_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_first_day_of_month'>;
}
declare module 'date-fns/is_friday/index.js' {
  declare module.exports: $Exports<'date-fns/is_friday'>;
}
declare module 'date-fns/is_future/index.js' {
  declare module.exports: $Exports<'date-fns/is_future'>;
}
declare module 'date-fns/is_last_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_last_day_of_month'>;
}
declare module 'date-fns/is_leap_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_leap_year'>;
}
declare module 'date-fns/is_monday/index.js' {
  declare module.exports: $Exports<'date-fns/is_monday'>;
}
declare module 'date-fns/is_past/index.js' {
  declare module.exports: $Exports<'date-fns/is_past'>;
}
declare module 'date-fns/is_same_day/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_day'>;
}
declare module 'date-fns/is_same_hour/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_hour'>;
}
declare module 'date-fns/is_same_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_iso_week'>;
}
declare module 'date-fns/is_same_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_iso_year'>;
}
declare module 'date-fns/is_same_minute/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_minute'>;
}
declare module 'date-fns/is_same_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_month'>;
}
declare module 'date-fns/is_same_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_quarter'>;
}
declare module 'date-fns/is_same_second/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_second'>;
}
declare module 'date-fns/is_same_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_week'>;
}
declare module 'date-fns/is_same_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_year'>;
}
declare module 'date-fns/is_saturday/index.js' {
  declare module.exports: $Exports<'date-fns/is_saturday'>;
}
declare module 'date-fns/is_sunday/index.js' {
  declare module.exports: $Exports<'date-fns/is_sunday'>;
}
declare module 'date-fns/is_this_hour/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_hour'>;
}
declare module 'date-fns/is_this_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_iso_week'>;
}
declare module 'date-fns/is_this_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_iso_year'>;
}
declare module 'date-fns/is_this_minute/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_minute'>;
}
declare module 'date-fns/is_this_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_month'>;
}
declare module 'date-fns/is_this_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_quarter'>;
}
declare module 'date-fns/is_this_second/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_second'>;
}
declare module 'date-fns/is_this_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_week'>;
}
declare module 'date-fns/is_this_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_year'>;
}
declare module 'date-fns/is_thursday/index.js' {
  declare module.exports: $Exports<'date-fns/is_thursday'>;
}
declare module 'date-fns/is_today/index.js' {
  declare module.exports: $Exports<'date-fns/is_today'>;
}
declare module 'date-fns/is_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/is_tomorrow'>;
}
declare module 'date-fns/is_tuesday/index.js' {
  declare module.exports: $Exports<'date-fns/is_tuesday'>;
}
declare module 'date-fns/is_valid/index.js' {
  declare module.exports: $Exports<'date-fns/is_valid'>;
}
declare module 'date-fns/is_wednesday/index.js' {
  declare module.exports: $Exports<'date-fns/is_wednesday'>;
}
declare module 'date-fns/is_weekend/index.js' {
  declare module.exports: $Exports<'date-fns/is_weekend'>;
}
declare module 'date-fns/is_within_range/index.js' {
  declare module.exports: $Exports<'date-fns/is_within_range'>;
}
declare module 'date-fns/is_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/is_yesterday'>;
}
declare module 'date-fns/last_day_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_iso_week'>;
}
declare module 'date-fns/last_day_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_iso_year'>;
}
declare module 'date-fns/last_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_month'>;
}
declare module 'date-fns/last_day_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_quarter'>;
}
declare module 'date-fns/last_day_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_week'>;
}
declare module 'date-fns/last_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_year'>;
}
declare module 'date-fns/locale/_lib/build_formatting_tokens_reg_exp/index.js' {
  declare module.exports: $Exports<'date-fns/locale/_lib/build_formatting_tokens_reg_exp'>;
}
declare module 'date-fns/locale/ar/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ar/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar/build_format_locale'>;
}
declare module 'date-fns/locale/ar/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar'>;
}
declare module 'date-fns/locale/bg/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/bg/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg/build_format_locale'>;
}
declare module 'date-fns/locale/bg/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg'>;
}
declare module 'date-fns/locale/ca/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ca/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca/build_format_locale'>;
}
declare module 'date-fns/locale/ca/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca'>;
}
declare module 'date-fns/locale/cs/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/cs/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs/build_format_locale'>;
}
declare module 'date-fns/locale/cs/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs'>;
}
declare module 'date-fns/locale/da/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/da/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da/build_format_locale'>;
}
declare module 'date-fns/locale/da/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da'>;
}
declare module 'date-fns/locale/de/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/de/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de/build_format_locale'>;
}
declare module 'date-fns/locale/de/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de'>;
}
declare module 'date-fns/locale/el/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/el/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el/build_format_locale'>;
}
declare module 'date-fns/locale/el/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el'>;
}
declare module 'date-fns/locale/en/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/en/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en/build_format_locale'>;
}
declare module 'date-fns/locale/en/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en'>;
}
declare module 'date-fns/locale/eo/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/eo/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo/build_format_locale'>;
}
declare module 'date-fns/locale/eo/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo'>;
}
declare module 'date-fns/locale/es/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/es/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es/build_format_locale'>;
}
declare module 'date-fns/locale/es/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es'>;
}
declare module 'date-fns/locale/fi/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/fi/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi/build_format_locale'>;
}
declare module 'date-fns/locale/fi/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi'>;
}
declare module 'date-fns/locale/fil/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/fil/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil/build_format_locale'>;
}
declare module 'date-fns/locale/fil/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil'>;
}
declare module 'date-fns/locale/fr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/fr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr/build_format_locale'>;
}
declare module 'date-fns/locale/fr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr'>;
}
declare module 'date-fns/locale/hr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/hr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr/build_format_locale'>;
}
declare module 'date-fns/locale/hr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr'>;
}
declare module 'date-fns/locale/hu/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/hu/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu/build_format_locale'>;
}
declare module 'date-fns/locale/hu/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu'>;
}
declare module 'date-fns/locale/id/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/id/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id/build_format_locale'>;
}
declare module 'date-fns/locale/id/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id'>;
}
declare module 'date-fns/locale/is/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/is/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is/build_format_locale'>;
}
declare module 'date-fns/locale/is/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is'>;
}
declare module 'date-fns/locale/it/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/it/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it/build_format_locale'>;
}
declare module 'date-fns/locale/it/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it'>;
}
declare module 'date-fns/locale/ja/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ja/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja/build_format_locale'>;
}
declare module 'date-fns/locale/ja/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja'>;
}
declare module 'date-fns/locale/ko/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ko/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko/build_format_locale'>;
}
declare module 'date-fns/locale/ko/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko'>;
}
declare module 'date-fns/locale/mk/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/mk/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk/build_format_locale'>;
}
declare module 'date-fns/locale/mk/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk'>;
}
declare module 'date-fns/locale/nb/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/nb/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb/build_format_locale'>;
}
declare module 'date-fns/locale/nb/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb'>;
}
declare module 'date-fns/locale/nl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/nl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl/build_format_locale'>;
}
declare module 'date-fns/locale/nl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl'>;
}
declare module 'date-fns/locale/pl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/pl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl/build_format_locale'>;
}
declare module 'date-fns/locale/pl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl'>;
}
declare module 'date-fns/locale/pt/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/pt/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt/build_format_locale'>;
}
declare module 'date-fns/locale/pt/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt'>;
}
declare module 'date-fns/locale/ro/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ro/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro/build_format_locale'>;
}
declare module 'date-fns/locale/ro/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro'>;
}
declare module 'date-fns/locale/ru/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/ru/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru/build_format_locale'>;
}
declare module 'date-fns/locale/ru/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru'>;
}
declare module 'date-fns/locale/sk/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/sk/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk/build_format_locale'>;
}
declare module 'date-fns/locale/sk/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk'>;
}
declare module 'date-fns/locale/sl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/sl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl/build_format_locale'>;
}
declare module 'date-fns/locale/sl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl'>;
}
declare module 'date-fns/locale/sv/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/sv/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv/build_format_locale'>;
}
declare module 'date-fns/locale/sv/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv'>;
}
declare module 'date-fns/locale/th/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/th/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th/build_format_locale'>;
}
declare module 'date-fns/locale/th/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th'>;
}
declare module 'date-fns/locale/tr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/tr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr/build_format_locale'>;
}
declare module 'date-fns/locale/tr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr'>;
}
declare module 'date-fns/locale/zh_cn/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/zh_cn/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn/build_format_locale'>;
}
declare module 'date-fns/locale/zh_cn/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn'>;
}
declare module 'date-fns/locale/zh_tw/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw/build_distance_in_words_locale'>;
}
declare module 'date-fns/locale/zh_tw/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw/build_format_locale'>;
}
declare module 'date-fns/locale/zh_tw/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw'>;
}
declare module 'date-fns/max/index.js' {
  declare module.exports: $Exports<'date-fns/max'>;
}
declare module 'date-fns/min/index.js' {
  declare module.exports: $Exports<'date-fns/min'>;
}
declare module 'date-fns/parse/index.js' {
  declare module.exports: $Exports<'date-fns/parse'>;
}
declare module 'date-fns/set_date/index.js' {
  declare module.exports: $Exports<'date-fns/set_date'>;
}
declare module 'date-fns/set_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_day_of_year'>;
}
declare module 'date-fns/set_day/index.js' {
  declare module.exports: $Exports<'date-fns/set_day'>;
}
declare module 'date-fns/set_hours/index.js' {
  declare module.exports: $Exports<'date-fns/set_hours'>;
}
declare module 'date-fns/set_iso_day/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_day'>;
}
declare module 'date-fns/set_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_week'>;
}
declare module 'date-fns/set_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_year'>;
}
declare module 'date-fns/set_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/set_milliseconds'>;
}
declare module 'date-fns/set_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/set_minutes'>;
}
declare module 'date-fns/set_month/index.js' {
  declare module.exports: $Exports<'date-fns/set_month'>;
}
declare module 'date-fns/set_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/set_quarter'>;
}
declare module 'date-fns/set_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/set_seconds'>;
}
declare module 'date-fns/set_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_year'>;
}
declare module 'date-fns/start_of_day/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_day'>;
}
declare module 'date-fns/start_of_hour/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_hour'>;
}
declare module 'date-fns/start_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_iso_week'>;
}
declare module 'date-fns/start_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_iso_year'>;
}
declare module 'date-fns/start_of_minute/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_minute'>;
}
declare module 'date-fns/start_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_month'>;
}
declare module 'date-fns/start_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_quarter'>;
}
declare module 'date-fns/start_of_second/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_second'>;
}
declare module 'date-fns/start_of_today/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_today'>;
}
declare module 'date-fns/start_of_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_tomorrow'>;
}
declare module 'date-fns/start_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_week'>;
}
declare module 'date-fns/start_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_year'>;
}
declare module 'date-fns/start_of_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_yesterday'>;
}
declare module 'date-fns/sub_days/index.js' {
  declare module.exports: $Exports<'date-fns/sub_days'>;
}
declare module 'date-fns/sub_hours/index.js' {
  declare module.exports: $Exports<'date-fns/sub_hours'>;
}
declare module 'date-fns/sub_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/sub_iso_years'>;
}
declare module 'date-fns/sub_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/sub_milliseconds'>;
}
declare module 'date-fns/sub_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/sub_minutes'>;
}
declare module 'date-fns/sub_months/index.js' {
  declare module.exports: $Exports<'date-fns/sub_months'>;
}
declare module 'date-fns/sub_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/sub_quarters'>;
}
declare module 'date-fns/sub_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/sub_seconds'>;
}
declare module 'date-fns/sub_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/sub_weeks'>;
}
declare module 'date-fns/sub_years/index.js' {
  declare module.exports: $Exports<'date-fns/sub_years'>;
}
